name: Development Firebase Deployment
on:
  push:
    branches:
      - 'dev'
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: '18'
      - name: Set Legacy SSL
        run: export NODE_OPTIONS=--openssl-legacy-provider
      - name: Install NPM Dependencies
        run: npm install
      - name: Build Application
        run: npm run build
      - name: Install Firebase Tools
        run: npm install firebase-tools -g
      - name: Deploy to Firebase Preview Channel
        run: firebase hosting:channel:deploy preview --project grocerieslist-app --token "${{ secrets.FIREBASE_TOKEN }}"
